name: Build docker image

on:
  push:
    branches:
      - main
      - feature/build-docker-image # Temporary branch for testing purposes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: regenerate-docker-ignore
        name: Regenerate .dockerignore based on other files
        run: |
          cat .gitignore > .dockerignore
          cat .aws.ignore >> .dockerignore

      - id: build-docker-image
        name: Build docker image
        run: |
          docker build -t gs_simit .
